#!/usr/bin/env php
<?php

if(isset($argv[1]) && 'config' == $argv[1]) {
  echo "graph_title Lichess JVM threads
graph_args --base 1000 -l 0
graph_vlabel threads
graph_category lichess
threads.label threads
threads.draw LINE
";
  exit;
}

$url = 'http://en.lichess.org/monitor/status/threads';

$curl = curl_init();
curl_setopt_array($curl, array(
      CURLOPT_URL             => $url,
      CURLOPT_PORT            => 80,
      CURLOPT_USERAGENT       => 'munin',
      CURLOPT_RETURNTRANSFER  => true,
      CURLOPT_TIMEOUT         => 2
    ));
$threads = curl_exec($curl);

echo "threads.value ".$threads."\n";
